// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import Foundation.NSURLSession;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class XmlRoot;
@class XmlElement;
@class XmlAttribute;
@class NSError;

SWIFT_CLASS("_TtC10AnetDomain11DomainModel")
@interface DomainModel : NSObject
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
- (NSString * __nullable)objectForKeyedSubscript:(NSString * __nonnull)key;
- (void)setObject:(NSString * __nullable)value forKeyedSubscript:(NSString * __nonnull)key;
- (NSString * __nonnull)toXmlString;
- (NSError * __nullable)deserialize:(NSString * __nonnull)xmlString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AttributeType;
@class NSNumber;

SWIFT_CLASS("_TtC10AnetDomain18AttributeArrayType")
@interface AttributeArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<AttributeType *> * __nullable attribute;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain13AttributeType")
@interface AttributeType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nonnull key;
@property (nonatomic, copy) NSString * __nullable value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain7XmlEnum")
@interface XmlEnum : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull value;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id __nullable)object;
@property (nonatomic, readonly, copy) NSString * __nonnull description;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain22AuthenticationKindEnum")
@interface AuthenticationKindEnum : XmlEnum
+ (AuthenticationKindEnum * __nonnull)Password;
+ (AuthenticationKindEnum * __nonnull)Session;
+ (AuthenticationKindEnum * __nonnull)Digest;
+ (AuthenticationKindEnum * __nonnull)Key;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain31AuthenticationRequestMethodEnum")
@interface AuthenticationRequestMethodEnum : XmlEnum
+ (AuthenticationRequestMethodEnum * __nonnull)Login;
+ (AuthenticationRequestMethodEnum * __nonnull)Logout;
+ (AuthenticationRequestMethodEnum * __nonnull)Register;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain8BaseType")
@interface BaseType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<AttributeType *> * __nullable attributes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain22TransactionPayloadType")
@interface TransactionPayloadType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain29TransactionRequestPayloadType")
@interface TransactionRequestPayloadType : TransactionPayloadType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain25AuthenticationRequestType")
@interface AuthenticationRequestType : TransactionRequestPayloadType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) AuthenticationRequestMethodEnum * __nonnull method;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain30TransactionResponsePayloadType")
@interface TransactionResponsePayloadType : TransactionPayloadType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain26AuthenticationResponseType")
@interface AuthenticationResponseType : TransactionResponsePayloadType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) AuthenticationRequestMethodEnum * __nullable method;
@property (nonatomic, copy) NSArray<NSString *> * __nullable permissions;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MobileDeviceInfoType;

SWIFT_CLASS("_TtC10AnetDomain18AuthenticationType")
@interface AuthenticationType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nullable userName;
@property (nonatomic, copy) NSString * __nullable accountID;
@property (nonatomic, strong) AuthenticationKindEnum * __nonnull authKind;
@property (nonatomic, copy) NSString * __nonnull authData;
@property (nonatomic, strong) MobileDeviceInfoType * __nullable mobileDeviceInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class ContactKindEnum;

SWIFT_CLASS("_TtC10AnetDomain15ContactKindType")
@interface ContactKindType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) ContactKindEnum * __nonnull kind;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain18ContactAddressType")
@interface ContactAddressType : ContactKindType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nullable addressLabel;
@property (nonatomic, copy) NSString * __nullable address1;
@property (nonatomic, copy) NSString * __nullable address2;
@property (nonatomic, copy) NSString * __nullable city;
@property (nonatomic, copy) NSString * __nullable state;
@property (nonatomic, copy) NSString * __nullable postalCode;
@property (nonatomic, copy) NSString * __nullable country;
@property (nonatomic, copy) NSString * __nullable province;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain23ContactEmailAddressType")
@interface ContactEmailAddressType : ContactKindType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nonnull email;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ContactInfoType;

SWIFT_CLASS("_TtC10AnetDomain20ContactInfoArrayType")
@interface ContactInfoArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<ContactInfoType *> * __nullable contact;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ContactPhoneNumberType;

SWIFT_CLASS("_TtC10AnetDomain15ContactInfoType")
@interface ContactInfoType : ContactKindType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nullable companyName;
@property (nonatomic, copy) NSString * __nonnull firstName;
@property (nonatomic, copy) NSString * __nonnull lastName;
@property (nonatomic, copy) NSString * __nullable title;
@property (nonatomic, copy) NSArray<ContactAddressType *> * __nullable addresses;
@property (nonatomic, copy) NSArray<ContactPhoneNumberType *> * __nullable phoneNumbers;
@property (nonatomic, copy) NSArray<ContactEmailAddressType *> * __nullable emailAddresses;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain15ContactKindEnum")
@interface ContactKindEnum : XmlEnum
+ (ContactKindEnum * __nonnull)Private;
+ (ContactKindEnum * __nonnull)Personal;
+ (ContactKindEnum * __nonnull)Home;
+ (ContactKindEnum * __nonnull)Work;
+ (ContactKindEnum * __nonnull)Mobile;
+ (ContactKindEnum * __nonnull)Fax;
+ (ContactKindEnum * __nonnull)Business;
+ (ContactKindEnum * __nonnull)Billing;
+ (ContactKindEnum * __nonnull)Shipping;
+ (ContactKindEnum * __nonnull)Other;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10AnetDomain22ContactPhoneNumberType")
@interface ContactPhoneNumberType : ContactKindType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nonnull number;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CreditCardIssuerInfo;
@class PaymentCardType;

SWIFT_CLASS("_TtC10AnetDomain14CreditCardInfo")
@interface CreditCardInfo : NSObject
+ (CreditCardIssuerInfo * __nonnull)AmericanExpress;
+ (CreditCardIssuerInfo * __nonnull)DinersClub;
+ (CreditCardIssuerInfo * __nonnull)Discover;
+ (CreditCardIssuerInfo * __nonnull)JCB;
+ (CreditCardIssuerInfo * __nonnull)MasterCard;
+ (CreditCardIssuerInfo * __nonnull)Visa;
@property (nonatomic, readonly, strong) PaymentCardType * __null_unspecified paymentCard;
@property (nonatomic, readonly, strong) CreditCardIssuerInfo * __null_unspecified issuerInfo;
@property (nonatomic, copy) NSString * __nullable billingZipcode;
- (nonnull instancetype)initWithPaymentCard:(PaymentCardType * __null_unspecified)paymentCard issuerInfo:(CreditCardIssuerInfo * __null_unspecified)issuerInfo OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)maskAccountNumber:(unichar)maskChar;
@end


SWIFT_CLASS("_TtC10AnetDomain20CreditCardIssuerInfo")
@interface CreditCardIssuerInfo : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull issuerName;
@property (nonatomic, readonly) NSUInteger securityCodeRequiredDigits;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * __nonnull accountNumberRequiredDigits;
@property (nonatomic, readonly, copy) NSArray<NSArray<NSNumber *> *> * __nonnull accountNumberIdentityDigits;
@end


SWIFT_CLASS("_TtC10AnetDomain19CreditCardValidator")
@interface CreditCardValidator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain18CurrencyAmountType")
@interface CurrencyAmountType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) NSNumber * __nonnull amount;
@property (nonatomic, strong) NSNumber * __nullable decimalPlaces;
@property (nonatomic, copy) NSString * __nullable code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class NSExtensionItem;
@class PaymentRequestType;

SWIFT_CLASS("_TtC10AnetDomain14GatewayService")
@interface GatewayService : NSObject
+ (NSString * __nonnull)kUTIPaymentRequestCardReader;
+ (NSString * __nonnull)kUTIPaymentResponse;
+ (NSString * __nonnull)kKeyPaymentRequestAmount;
+ (NSString * __nonnull)kKeyPaymentRequestXml;
+ (NSString * __nonnull)kKeyPaymentResponseXml;
+ (NSString * __nonnull)kKeyPaymentChoiceResponseXml;
+ (NSExtensionItem * __nonnull)createPaymentAmountExtensionItem:(double)amount;
+ (NSExtensionItem * __nonnull)createPaymentRequestExtensionItem:(PaymentRequestType * __nonnull)paymentRequest;
+ (BOOL)loadPaymentResponse:(NSExtensionItem * __nonnull)extensionItem completion:(void (^ __nonnull)(DomainModel * __nullable, NSError * __nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
@class NSURLRequest;
@class NSMutableURLRequest;
@class NSData;
@class NSURLSessionTask;
@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;
@class NSHTTPURLResponse;
@class NSURLSessionDataTask;

SWIFT_CLASS("_TtC10AnetDomain14GatewaySession")
@interface GatewaySession : NSObject <NSURLSessionTaskDelegate, NSURLSessionDelegate>
@property (nonatomic, readonly, strong) NSURL * __nonnull url;
@property (nonatomic, readonly, copy) NSString * __nonnull name;
@property (nonatomic) NSUInteger requestContentEncoding;
@property (nonatomic) BOOL suspended;
@property (nonatomic, readonly) NSInteger taskCount;
- (nonnull instancetype)initWithName:(NSString * __nonnull)name url:(NSURL * __nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (void)cancelAllTasks;
- (NSURLRequest * __nullable)prepareSoapRequest:(NSString * __nonnull)soapAction soapMessage:(NSString * __nonnull)soapMessage;
- (NSMutableURLRequest * __nullable)prepareHttpRequest:(NSString * __nonnull)httpMethod httpContent:(NSString * __nullable)httpContent;
- (NSMutableURLRequest * __nullable)prepareHttpRequest:(NSString * __nonnull)httpMethod httpContentData:(NSData * __nullable)httpContentData;
- (NSURLSessionTask * __nullable)sendRequest:(NSURLRequest * __nonnull)request completion:(void (^ __nonnull)(NSData * __nullable, NSError * __nullable))completion;
- (void)URLSession:(NSURLSession * __nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * __nonnull)challenge completionHandler:(void (^ __nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * __nullable))completionHandler;
- (void)URLSession:(NSURLSession * __nonnull)session task:(NSURLSessionTask * __nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * __nonnull)response newRequest:(NSURLRequest * __nonnull)request completionHandler:(void (^ __nonnull)(NSURLRequest * __nullable))completionHandler;
- (void)URLSession:(NSURLSession * __nonnull)session dataTask:(NSURLSessionDataTask * __nonnull)dataTask didReceiveData:(NSData * __nonnull)data;
- (void)URLSession:(NSURLSession * __nonnull)session task:(NSURLSessionTask * __nonnull)task didCompleteWithError:(NSError * __nullable)error;
@end


SWIFT_CLASS("_TtC10AnetDomain15GatewaySettings")
@interface GatewaySettings : NSObject
+ (NSString * __nonnull)defaultCurrency;
+ (void)setDefaultCurrency:(NSString * __nonnull)value;
+ (BOOL)testMode;
+ (void)setTestMode:(BOOL)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MessageType;

SWIFT_CLASS("_TtC10AnetDomain16MessageArrayType")
@interface MessageArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<MessageType *> * __nullable message;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain15MessageKindEnum")
@interface MessageKindEnum : XmlEnum
+ (MessageKindEnum * __nonnull)Unknown;
+ (MessageKindEnum * __nonnull)Info;
+ (MessageKindEnum * __nonnull)Warning;
+ (MessageKindEnum * __nonnull)Error;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain11MessageType")
@interface MessageType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) MessageKindEnum * __nonnull kind;
@property (nonatomic, copy) NSString * __nonnull code;
@property (nonatomic, copy) NSString * __nonnull desc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class XmlAnyObject;

@interface MessageType (SWIFT_EXTENSION(AnetDomain))
- (nullable instancetype)initWithMessageType:(NSString * __nonnull)messageType icsMessage:(XmlAnyObject * __nullable)icsMessage;
@end

@class MobileDeviceOptionEnum;

SWIFT_CLASS("_TtC10AnetDomain20MobileDeviceInfoType")
@interface MobileDeviceInfoType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nonnull deviceID;
@property (nonatomic, copy) NSString * __nullable desc;
@property (nonatomic, copy) NSString * __nullable phoneNumber;
@property (nonatomic, copy) NSString * __nullable platformDescription;
@property (nonatomic, strong) MobileDeviceOptionEnum * __nonnull deviceOption;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain22MobileDeviceOptionEnum")
@interface MobileDeviceOptionEnum : XmlEnum
+ (MobileDeviceOptionEnum * __nonnull)Register;
+ (MobileDeviceOptionEnum * __nonnull)Disable;
+ (MobileDeviceOptionEnum * __nonnull)Activate;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end

@class OrderItemType;
@class OrderSummaryItemType;

SWIFT_CLASS("_TtC10AnetDomain13OrderInfoType")
@interface OrderInfoType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nullable orderNumber;
@property (nonatomic, copy) NSString * __nullable referenceNumber;
@property (nonatomic, copy) NSString * __nullable desc;
@property (nonatomic, copy) NSArray<OrderItemType *> * __nullable orderItems;
@property (nonatomic, copy) NSArray<OrderSummaryItemType *> * __nullable orderSummaryItems;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain18OrderItemArrayType")
@interface OrderItemArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<OrderItemType *> * __nullable orderItem;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDecimalNumber;

SWIFT_CLASS("_TtC10AnetDomain13OrderItemType")
@interface OrderItemType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nullable code;
@property (nonatomic, copy) NSString * __nonnull name;
@property (nonatomic, copy) NSString * __nullable desc;
@property (nonatomic, strong) NSDecimalNumber * __nonnull quantity;
@property (nonatomic, strong) NSDecimalNumber * __nonnull unitPrice;
@property (nonatomic, strong) NSNumber * __nullable taxable;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain25OrderSummaryItemArrayType")
@interface OrderSummaryItemArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<OrderSummaryItemType *> * __nullable orderSummaryItem;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain24OrderSummaryItemKindEnum")
@interface OrderSummaryItemKindEnum : XmlEnum
+ (OrderSummaryItemKindEnum * __nonnull)Tax;
+ (OrderSummaryItemKindEnum * __nonnull)Duty;
+ (OrderSummaryItemKindEnum * __nonnull)Shipping;
+ (OrderSummaryItemKindEnum * __nonnull)Subtotal;
+ (OrderSummaryItemKindEnum * __nonnull)Tip;
+ (OrderSummaryItemKindEnum * __nonnull)Total;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain20OrderSummaryItemType")
@interface OrderSummaryItemType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) OrderSummaryItemKindEnum * __nonnull kind;
@property (nonatomic, strong) NSDecimalNumber * __nonnull amount;
@property (nonatomic, copy) NSString * __nullable name;
@property (nonatomic, copy) NSString * __nullable desc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PaymentKindEnum;
@class PaymentMethodEnum;

SWIFT_CLASS("_TtC10AnetDomain11PaymentType")
@interface PaymentType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) PaymentKindEnum * __nonnull kind;
@property (nonatomic, strong) PaymentMethodEnum * __nonnull method;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain15PaymentCardType")
@interface PaymentCardType : PaymentType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nonnull accountNumber;
@property (nonatomic, copy) NSString * __nonnull expirationDate;
@property (nonatomic, copy) NSString * __nullable securityCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain17PaymentChoiceType")
@interface PaymentChoiceType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) PaymentType * __nullable item;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain15PaymentKindEnum")
@interface PaymentKindEnum : XmlEnum
+ (PaymentKindEnum * __nonnull)CP;
+ (PaymentKindEnum * __nonnull)CNP;
+ (PaymentKindEnum * __nonnull)Internet;
+ (PaymentKindEnum * __nonnull)POS;
+ (PaymentKindEnum * __nonnull)EMV;
+ (PaymentKindEnum * __nonnull)InApp;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain17PaymentMethodEnum")
@interface PaymentMethodEnum : XmlEnum
+ (PaymentMethodEnum * __nonnull)Secure;
+ (PaymentMethodEnum * __nonnull)Cash;
+ (PaymentMethodEnum * __nonnull)Credit;
+ (PaymentMethodEnum * __nonnull)Debit;
+ (PaymentMethodEnum * __nonnull)Check;
+ (PaymentMethodEnum * __nonnull)Bank;
+ (PaymentMethodEnum * __nonnull)PayPal;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain24PaymentRequestMethodEnum")
@interface PaymentRequestMethodEnum : XmlEnum
+ (PaymentRequestMethodEnum * __nonnull)Authorize;
+ (PaymentRequestMethodEnum * __nonnull)Sale;
+ (PaymentRequestMethodEnum * __nonnull)Void;
+ (PaymentRequestMethodEnum * __nonnull)Refund;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain18PaymentRequestType")
@interface PaymentRequestType : TransactionRequestPayloadType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) PaymentRequestMethodEnum * __nonnull method;
@property (nonatomic, copy) NSString * __nullable referenceID;
@property (nonatomic, copy) NSString * __nullable splitTenderID;
@property (nonatomic, strong) PaymentChoiceType * __nullable payment;
@property (nonatomic, strong) CurrencyAmountType * __nonnull amount;
@property (nonatomic, strong) NSNumber * __nonnull partial;
@property (nonatomic, strong) OrderInfoType * __nullable order;
@property (nonatomic, copy) NSArray<ContactInfoType *> * __nullable contacts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain19PaymentResponseType")
@interface PaymentResponseType : TransactionResponsePayloadType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) PaymentRequestMethodEnum * __nullable method;
@property (nonatomic, strong) NSNumber * __nullable resultCode;
@property (nonatomic, strong) NSNumber * __nullable transactionID;
@property (nonatomic, copy) NSString * __nullable transactionHash;
@property (nonatomic, copy) NSString * __nullable authorizationCode;
@property (nonatomic, copy) NSString * __nullable requestID;
@property (nonatomic, copy) NSString * __nullable reconciliationID;
@property (nonatomic, copy) NSArray<MessageType *> * __nullable messages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain21PaymentSecureKindEnum")
@interface PaymentSecureKindEnum : XmlEnum
+ (PaymentSecureKindEnum * __nonnull)SwipedData;
+ (PaymentSecureKindEnum * __nonnull)CommonTracks;
+ (PaymentSecureKindEnum * __nonnull)EmvData;
+ (PaymentSecureKindEnum * __nonnull)ApplePayToken;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end

@class SecureDataType;

SWIFT_CLASS("_TtC10AnetDomain17PaymentSecureType")
@interface PaymentSecureType : PaymentType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) PaymentSecureKindEnum * __nonnull secureKind;
@property (nonatomic, strong) SecureDataType * __nonnull secureData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain23PaymentSubscriptionType")
@interface PaymentSubscriptionType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) NSNumber * __nonnull subscriptionID;
@property (nonatomic, strong) NSNumber * __nonnull subscriptionNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10AnetDomain19PermissionArrayType")
@interface PermissionArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<NSString *> * __nullable permission;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain16ResponseCodeEnum")
@interface ResponseCodeEnum : XmlEnum
+ (ResponseCodeEnum * __nonnull)Unknown;
+ (ResponseCodeEnum * __nonnull)Success;
+ (ResponseCodeEnum * __nonnull)Pending;
+ (ResponseCodeEnum * __nonnull)Incomplete;
+ (ResponseCodeEnum * __nonnull)Error;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end

@class ReturnedOrderItemType;

SWIFT_CLASS("_TtC10AnetDomain26ReturnedOrderItemArrayType")
@interface ReturnedOrderItemArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<ReturnedOrderItemType *> * __nullable returnedOrderItem;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;

SWIFT_CLASS("_TtC10AnetDomain21ReturnedOrderItemType")
@interface ReturnedOrderItemType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nonnull itemID;
@property (nonatomic, strong) NSDate * __nonnull dateTimeUTC;
@property (nonatomic, copy) NSString * __nonnull code;
@property (nonatomic, copy) NSString * __nonnull desc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain18SecureDataAlgoEnum")
@interface SecureDataAlgoEnum : XmlEnum
+ (SecureDataAlgoEnum * __nonnull)TDES;
+ (SecureDataAlgoEnum * __nonnull)AES;
+ (SecureDataAlgoEnum * __nonnull)RSA;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain22SecureDataEncodingEnum")
@interface SecureDataEncodingEnum : XmlEnum
+ (SecureDataEncodingEnum * __nonnull)Base64;
+ (SecureDataEncodingEnum * __nonnull)Hex;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain14SecureDataType")
@interface SecureDataType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) SecureDataEncodingEnum * __nonnull encoding;
@property (nonatomic, strong) SecureDataAlgoEnum * __nonnull algorithm;
@property (nonatomic, copy) NSString * __nonnull formatMetadata;
@property (nonatomic, copy) NSString * __nonnull encryptedData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain9SoapFault")
@interface SoapFault : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nonnull faultCode;
@property (nonatomic, copy) NSString * __nonnull faultString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransactionBatchType;

SWIFT_CLASS("_TtC10AnetDomain25TransactionBatchArrayType")
@interface TransactionBatchArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<TransactionBatchType *> * __nullable batch;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransactionBatchStatisticType;

SWIFT_CLASS("_TtC10AnetDomain34TransactionBatchStatisticArrayType")
@interface TransactionBatchStatisticArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<TransactionBatchStatisticType *> * __nullable batch;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain29TransactionBatchStatisticType")
@interface TransactionBatchStatisticType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain20TransactionBatchType")
@interface TransactionBatchType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) NSNumber * __nonnull batchID;
@property (nonatomic, strong) NSDate * __nullable dateTimeUTC;
@property (nonatomic, copy) NSString * __nonnull status;
@property (nonatomic, copy) NSArray<TransactionBatchStatisticType *> * __nullable statistics;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransactionReportMethodEnum;

SWIFT_CLASS("_TtC10AnetDomain29TransactionReportResponseType")
@interface TransactionReportResponseType : TransactionResponsePayloadType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) TransactionReportMethodEnum * __nullable method;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain36TransactionBatchedReportResponseType")
@interface TransactionBatchedReportResponseType : TransactionReportResponseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<TransactionBatchType *> * __nullable batches;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransactionDetailType;

SWIFT_CLASS("_TtC10AnetDomain35TransactionDetailReportResponseType")
@interface TransactionDetailReportResponseType : TransactionReportResponseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) TransactionDetailType * __nullable transaction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain22TransactionSummaryType")
@interface TransactionSummaryType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) NSNumber * __nonnull transactionID;
@property (nonatomic, strong) NSDate * __nonnull dateTimeUTC;
@property (nonatomic, copy) NSString * __nullable transactionType;
@property (nonatomic, copy) NSString * __nonnull status;
@property (nonatomic, strong) NSDecimalNumber * __nonnull amount;
@property (nonatomic, strong) NSNumber * __nonnull hasReturnedItems;
@property (nonatomic, strong) PaymentSubscriptionType * __nullable paymentSubscription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain21TransactionDetailType")
@interface TransactionDetailType : TransactionSummaryType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSString * __nullable referenceID;
@property (nonatomic, copy) NSString * __nullable splitTenderID;
@property (nonatomic, strong) NSNumber * __nullable resultCode;
@property (nonatomic, copy) NSString * __nullable authorizationCode;
@property (nonatomic, strong) NSDecimalNumber * __nonnull authorizedAmount;
@property (nonatomic, strong) NSDecimalNumber * __nullable requestedAmount;
@property (nonatomic, strong) NSDecimalNumber * __nullable remainingBalance;
@property (nonatomic, strong) NSNumber * __nullable taxExempt;
@property (nonatomic, strong) PaymentChoiceType * __nullable payment;
@property (nonatomic, strong) TransactionBatchType * __nullable batch;
@property (nonatomic, strong) OrderInfoType * __nullable order;
@property (nonatomic, copy) NSArray<ReturnedOrderItemType *> * __nullable returnedItems;
@property (nonatomic, copy) NSArray<ContactInfoType *> * __nullable contacts;
@property (nonatomic, copy) NSArray<MessageType *> * __nullable messages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain19TransactionKindEnum")
@interface TransactionKindEnum : XmlEnum
+ (TransactionKindEnum * __nonnull)Authentication;
+ (TransactionKindEnum * __nonnull)Payment;
+ (TransactionKindEnum * __nonnull)Report;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10AnetDomain34TransactionReportContactChoiceType")
@interface TransactionReportContactChoiceType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) ContactKindType * __nullable item;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain27TransactionReportMethodEnum")
@interface TransactionReportMethodEnum : XmlEnum
+ (TransactionReportMethodEnum * __nonnull)Pending;
+ (TransactionReportMethodEnum * __nonnull)Completed;
+ (TransactionReportMethodEnum * __nonnull)Batched;
+ (TransactionReportMethodEnum * __nonnull)Detail;
+ (TransactionReportMethodEnum * __nonnull)Receipt;
- (nonnull instancetype)initWithValue:(NSString * __nonnull)value OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain28TransactionReportRequestType")
@interface TransactionReportRequestType : TransactionRequestPayloadType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) TransactionReportMethodEnum * __nonnull method;
@property (nonatomic, copy) NSString * __nullable subjectID;
@property (nonatomic, strong) TransactionReportContactChoiceType * __nullable contact;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10AnetDomain35TransactionRequestPayloadChoiceType")
@interface TransactionRequestPayloadChoiceType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) TransactionRequestPayloadType * __nullable item;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10AnetDomain15TransactionType")
@interface TransactionType : BaseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) TransactionKindEnum * __nonnull kind;
@property (nonatomic, copy) NSString * __nullable transactionID;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain22TransactionRequestType")
@interface TransactionRequestType : TransactionType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) AuthenticationType * __nonnull authentication;
@property (nonatomic, strong) TransactionRequestPayloadChoiceType * __nonnull payload;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain36TransactionResponsePayloadChoiceType")
@interface TransactionResponsePayloadChoiceType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) TransactionResponsePayloadType * __nullable item;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10AnetDomain23TransactionResponseType")
@interface TransactionResponseType : TransactionType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, strong) ResponseCodeEnum * __nonnull responseCode;
@property (nonatomic, copy) NSArray<MessageType *> * __nullable messages;
@property (nonatomic, strong) AuthenticationType * __nullable authentication;
@property (nonatomic, strong) TransactionResponsePayloadChoiceType * __nullable payload;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain27TransactionSummaryArrayType")
@interface TransactionSummaryArrayType : DomainModel
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<TransactionSummaryType *> * __nullable transaction;
@property (nonatomic, strong) NSNumber * __nullable length;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain36TransactionSummaryReportResponseType")
@interface TransactionSummaryReportResponseType : TransactionReportResponseType
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
@property (nonatomic, readonly, copy) NSArray<XmlAttribute *> * __nonnull xmlAttributes;
@property (nonatomic, copy) NSArray<TransactionSummaryType *> * __nullable transactions;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class XmlNamespace;

SWIFT_CLASS("_TtC10AnetDomain12XmlAnyObject")
@interface XmlAnyObject : DomainModel
@property (nonatomic, copy) NSString * __nullable content;
- (nonnull instancetype)initWithElementName:(NSString * __nonnull)elementName namespace:(XmlNamespace * __nullable)namespace_ OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) XmlRoot * __nonnull xmlRoot;
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull xmlElements;
- (XmlAnyObject * __nullable)getValue:(NSString * __nonnull)elementName;
@end


SWIFT_CLASS("_TtC10AnetDomain9XmlSchema")
@interface XmlSchema : NSObject
@property (nonatomic, readonly, strong, getter=namespace) XmlNamespace * __nullable namespace_;
@end

@class NSMutableString;

SWIFT_CLASS("_TtC10AnetDomain12XmlAttribute")
@interface XmlAttribute : XmlSchema
@property (nonatomic, readonly, copy) NSString * __nonnull name;
- (BOOL)isSameName:(NSString * __nonnull)name nsURI:(NSString * __null_unspecified)nsURI;
- (void)format:(NSMutableString * __nonnull)buffer ns:(XmlNamespace * __nullable)ns;
@end


SWIFT_CLASS("_TtC10AnetDomain10XmlElement")
@interface XmlElement : XmlSchema
@property (nonatomic, readonly, copy) NSString * __nonnull name;
- (BOOL)isElementName:(NSString * __nonnull)name namespaceURI:(NSString * __nullable)namespaceURI;
- (void)format:(NSMutableString * __nonnull)buffer ns:(XmlNamespace * __nullable)ns closeTag:(BOOL)closeTag;
@end


SWIFT_CLASS("_TtC10AnetDomain15XmlElementValue")
@interface XmlElementValue : XmlElement
@end


SWIFT_CLASS("_TtC10AnetDomain13XmlElementAny")
@interface XmlElementAny : XmlElementValue
@end


SWIFT_CLASS("_TtC10AnetDomain18XmlElementAnyValue")
@interface XmlElementAnyValue : XmlElementAny
- (nonnull instancetype)initWithName:(NSString * __nonnull)name namespaceURI:(NSString * __nullable)namespaceURI;
@end


SWIFT_CLASS("_TtC10AnetDomain15XmlElementArray")
@interface XmlElementArray : XmlElementValue
@property (nonatomic, readonly, strong) XmlElement * __nonnull arrayElement;
@property (nonatomic, readonly) BOOL isInline;
@end


SWIFT_CLASS("_TtC10AnetDomain16XmlElementChoice")
@interface XmlElementChoice : XmlElementValue
@property (nonatomic, readonly, copy) NSArray<XmlElement *> * __nonnull elements;
@end


SWIFT_CLASS("_TtC10AnetDomain17XmlElementContent")
@interface XmlElementContent : XmlElementValue
@end




SWIFT_CLASS("_TtC10AnetDomain12XmlNamespace")
@interface XmlNamespace : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull uri;
@property (nonatomic, readonly, copy) NSString * __nullable prefix;
- (nonnull instancetype)initWithUri:(NSString * __nonnull)uri prefix:(NSString * __nullable)prefix OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSUInteger hash;
@property (nonatomic, readonly, copy) NSString * __nonnull description;
- (BOOL)isEqual:(id __nullable)object;
- (void)format:(NSMutableString * __nonnull)buffer;
@end


SWIFT_CLASS("_TtC10AnetDomain7XmlRoot")
@interface XmlRoot : XmlElement
@end


@class NSCoder;

SWIFT_CLASS("_TtC10AnetDomain21XmlSerializationError")
@interface XmlSerializationError : NSError
+ (NSString * __nonnull)Domain;
- (nonnull instancetype)initWithCode:(NSInteger)code userInfo:(NSDictionary * __nullable)dict OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AnetDomain13XmlSerializer")
@interface XmlSerializer : NSObject
- (NSError * __nullable)deserialize:(DomainModel * __null_unspecified)model xmlString:(NSString * __null_unspecified)xmlString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
